### ISSUE TITLE
真是服了，最关键的一步作者没写

### ISSUE THREAD

**Issue by PHCSJC** [Jonnyan404/zerotier-planet#15]
docker-compose.yml，这个文件的MYADDR要修改为公网IP，教程里根本没写，搞了半天才发现

**Comment by Jonnyan404** [comment]
我又不是你爹妈，爱用不用。别在这抱怨。。。

要是提建议，就好好说话，别这么没教养！

**Comment by PHCSJC** [comment]
我来反馈，作者竟然如此说话，可见是个什么样的人，哈哈！

就这点东西又没什么技术含量，替代品多的事，已经换了

千万别把我反馈缺失的这一步写上，你要是敢写上，我就是你爹，我的帖子你可以删，但我会时常来看看儿子补没补，哈哈！

**Comment by Jonnyan404** [comment]
放心，不会删的。

既然没什么技术含量的东西，你都不会，可见跟傻子无异。

**Comment by PHCSJC** [comment]
哟，改个文件，再编译一下，再mv一下，好牛逼啊，还有会写dockerfile呢，下次再传到dockerhub，就更牛逼了喔！

就你这几步，还真把自己当回事了，笑死，哈哈！

**Comment by Jonnyan404** [comment]
哈哈哈哈哈哈哈，着实被你整开心了。

原谅你的不孝了，傻人有傻福就说的是你这样的吧

**Comment by PHCSJC** [comment]
怎么着？脑回路不正常了？开始自言自语了？自尊心受打击了？哈哈！

哟哟，别怕，你可牛逼了，这牛逼的东西，只有你会写喔，你会写mv,docker,compile呢，你还可以拿这来取消别人不会呢，哈哈！

**Comment by PHCSJC** [comment]
没有伞的孩子，必须努力奔跑喔

**Comment by PHCSJC** [comment]
来，发个付款码，请你喝一罐红牛喔，让你天天能迭代，日日可更新喔！

**Comment by PHCSJC** [comment]
小伙长的太瘦了，发个付款码，赞助你一下吧

**Comment by PHCSJC** [comment]
唯品会好玩吗？
