### ISSUE TITLE
什么情况会导致服务崩溃？

### ISSUE THREAD

**Issue by Jinming-Zhou** [Jonnyan404/zerotier-planet#17]
您好，

请教个问题。

我在上海的A机器上部署了您的这个项目，自建zerotier-planet，同时机器上还有一个MySQL数据库，我在北京的B机器上能够正常ping通A机器且稳定，根据zerotier-cli.bat peers 应该是走的中转的方式。

但是我从B机器上通过ZeroTier自建planet连接A机器的MySQL大量取数时，数据传到一半，会出现断联的情况，ping也不通。我重启A机器的ZeroTier服务能够恢复连接。多次试验下来皆是这个情况。

另一种情况是等待大概10分钟后也会断连，这时我去停止ZeroTier服务，会报“错误 1053：服务没有及时响应启动或控制请求”，重启服务也可以恢复连接。

请问可能是什么原因造成的？

感谢~

**Comment by Jonnyan404** [comment]
不清楚，不知道。
