### ISSUE TITLE
出现未知设备

### ISSUE THREAD

**Issue by caominyuan** [Jonnyan404/zerotier-planet#18]
配置好了, 出现一台未知设备, 一查ip地址是美国谷歌云的,
是怎么回事? 有后台?
<img width="279" alt="WeChatb84501abe7a36835024953bff6df1375" src="https://user-images.githubusercontent.com/26827161/192345671-e5313fc5-3b22-4fdf-bb90-691b9968faf9.png">

**Comment by caominyuan** [comment]
我的VPS是国内的(腾讯云学生机), 这个ip不是我的vps

**Comment by caominyuan** [comment]
![Screen Shot 2022-09-27 at 1 55 22 AM](https://user-images.githubusercontent.com/26827161/192346873-8a04535f-7f75-45cb-a2c1-9e189702cf4c.png)

**Comment by caominyuan** [comment]
mkmoonworld-x86_64是编译过的, 能不能公布源码呢

**Comment by Jonnyan404** [comment]
> mkmoonworld-x86_64是编译过的, 能不能公布源码呢

认真阅读文档，答案自现。
