### ISSUE TITLE
自建 zerotier planet 后，如何将服务器本身作为一个客户端加入网络？

### ISSUE THREAD

**Issue by shangdev** [Jonnyan404/zerotier-planet#19]
服务器 A ，使用 docker 自建了个 planet 行星服务器，新建 Network 网络 abc 。

本地电脑 B 加入 abc ；
现在要将服务器 A 也作为一个客户端，加入 abc ；

目的是内网互联。所以有办法使服务器 A 既作为 planet ，也作为 node 客户端吗？

**Comment by huaxianyan** [comment]
我也有这个疑问，看到这个 issue 想请教一下是怎么解决的

**Comment by shangdev** [comment]
@huaxianyan zerotier join xxx 就可以

**Comment by huaxianyan** [comment]
@shangdev 是进容器里 join 吗？

**Comment by huaxianyan** [comment]
@shangdev 进容器里 Join 了之后显示 500 OK，之后在 Web 管理界面里能看到一台新设备，但是 Peer status 显示的是 CONTROLLER，而且无法通过分配的内网 IP 访问到该 VPS 上的服务，请教一下是不是哪里有问题？

**Comment by shangdev** [comment]
@huaxianyan 显示CONTROLLER是正确的，join后控制面板勾选复选框了吗？

**Comment by huaxianyan** [comment]
@shangdev 勾选了，并且分配了 IP
![image](https://user-images.githubusercontent.com/19589248/222940312-25c0bd1b-357d-412c-8345-f498005963a4.png)

**Comment by wuchjun** [comment]
同样遇到这个问题，有没有解决方法

**Comment by TheSeaYouAreAllWater** [comment]
也遇到这种问题，没有办法解决吗？主要是端口被占用，也无法启用其他镜像吧
