### ISSUE TITLE
还是LEAF，PLANET没有生效

### ISSUE THREAD

**Issue by gotoin** [Jonnyan404/zerotier-planet#25]
按文档执行了下面的步骤
# 以下步骤为创建planet和moon
docker cp mkmoonworld-x86_64 ztncui:/tmp
docker cp patch.sh ztncui:/tmp
docker exec -it ztncui bash /tmp/patch.sh
docker restart ztncui

打开3180端口链接，只有moon下载，没有planet，从docker里面拷贝出来planet配制到客户端后，并没有生效，还是leaf

是我哪里操作有问题吗？
另外请问有办法删除官方planet吗，我想只保留自己的

**Comment by gotoin** [comment]
我尝试手动执行了下patch.sh:
报了以下错误:
1. /tmp/mkmoonworld-x86_64 moon.json
FATAL: kernel too old
Aborted (core dumped)

2. mkdir /var/lib/zerotier-one/moons.d
mkdir: cannot create directory '/var/lib/zerotier-one/moons.d': File exists

**Comment by Jonnyan404** [comment]
> 我尝试手动执行了下patch.sh: 报了以下错误:
> 
> 1. /tmp/mkmoonworld-x86_64 moon.json
>    FATAL: kernel too old
>    Aborted (core dumped)
> 2. mkdir /var/lib/zerotier-one/moons.d
>    mkdir: cannot create directory '/var/lib/zerotier-one/moons.d': File exists

这错误不是很明显么,`FATAL: kernel too old`,自行Google解决.
