### ISSUE TITLE
Members not able to communicate

### ISSUE THREAD

**Issue by MANKUD** [Jonnyan404/zerotier-planet#28]
I was successfully able to deploy this and was also able to join 2 members without any issues but the members are not able to communicate with each other nor ping each other also the ICMP echo request is allowed on both the members firewall. 

![image](https://user-images.githubusercontent.com/83474708/218869728-c8f1da13-8a83-4917-a6b9-d12d15105c22.png)

![image](https://user-images.githubusercontent.com/83474708/218869919-3c723e68-5ed8-41ab-9767-cf0aa90fd651.png)

![image](https://user-images.githubusercontent.com/83474708/218870060-dd5035cb-a82a-49b6-8644-5c0d2bc0fd7f.png)

![image](https://user-images.githubusercontent.com/83474708/218870086-acdf1a9b-53d4-4fcf-a049-e39ec9bc0b1f.png)

**Comment by MANKUD** [comment]
@Jonnyan404

**Comment by Jonnyan404** [comment]
I'm not sure either. Please refer to the Zerotier's official source code about Planet.

**Comment by MANKUD** [comment]
any idea why only one member shows leaf and the other one does not?

**Comment by Jonnyan404** [comment]
I don't know.
If you don't have any special needs,it's better that you use moon.

**Comment by MANKUD** [comment]
looks like you are not interested in helping anyway its ok thanks.

**Comment by Jonnyan404** [comment]
Sorry, my abilities are limited.
