### ISSUE TITLE
在armbian上安装好以后，找不到zerotier-planet这个目录

### ISSUE THREAD

**Issue by ftmis** [Jonnyan404/zerotier-planet#3]
在armbian上安装好以后，找不到zerotier-planet这个目录

**Comment by Jonnyan404** [comment]
> 在armbian上安装好以后，找不到zerotier-planet这个目录

这个目录在你执行 `git clone` 命令的目录下.

**Comment by ftmis** [comment]
> 

我搞错了，我是安装好了docker-compose ，好没执行 git clone
