### ISSUE TITLE
请求构建ARM镜像

### ISSUE THREAD

**Issue by lixingbu-tal** [Jonnyan404/zerotier-planet#31]
麻烦可以帮忙构建一个ARM的镜像吗 或者开源一下dockerfile文件 我自行构建也可

**Comment by simplove** [comment]
同求，另外请教下，端口改成非9993行不行？端口信息是写在planet里面的，还是其它文件

**Comment by Jonnyan404** [comment]
> 麻烦可以帮忙构建一个ARM的镜像吗 或者开源一下dockerfile文件 我自行构建也可

我已经在readme里说明了所有来源,认真阅读的话,肯定找的到.    没有arm镜像,是因为依赖的 
 https://github.com/kaaass/ZeroTierOne/releases/tag/mkmoonworld-1.0 没有arm程序.

**Comment by Jonnyan404** [comment]
> 同求，另外请教下，端口改成非9993行不行？端口信息是写在planet里面的，还是其它文件

因为 https://github.com/kaaass/ZeroTierOne/releases/tag/mkmoonworld-1.0  程序写死了,如果需要更改,需要自行打包.
