### ISSUE TITLE
建议添加Mac用户客户端文档

### ISSUE THREAD

**Issue by golowper** [Jonnyan404/zerotier-planet#35]
# Step1: 安装 zerotier 客户端
## Opt1: 推荐官网下载（可选方式一）

官方地址：https://www.zerotier.com/download/
官方下载地址：https://download.zerotier.com/dist/ZeroTier%20One.pkg
<img width="1318" alt="image" src="https://github.com/Jonnyan404/zerotier-planet/assets/77011000/7352196c-919d-49b6-b885-3017bb1d4a34">

## Opt2: brew 安装（可选方式二）

```bash
brew install --cask zerotier-one
```

# Step2 :  替换plant 文件

浏览器访问 `http://server-ip:3180` 打开planet和moon文件下载页面

替换 `/Library/Application Support/ZeroTier/One/planet` 文件
用命令行替换带空格路径记得加上引号

```bash
sudo curl http://server-ip:3180/planet > "/Library/Application Support/ZeroTier/One/planet"
```

# Step3: 重启zerotier-one 服务
建议直接 reboot

# Step4: 加入网络 zerotier-cli join 网络 id

可以直接通过图形化页面进行操作
<img width="599" alt="image" src="https://github.com/Jonnyan404/zerotier-planet/assets/77011000/e7f85406-067a-4ecc-b8e6-a3beb4b8f939">

或者 命令行

```bash
zerotier-cli join 网络id
```

# Step5: 管理后台同意加入请求  

后台配置详见文档：https://www.mrdoc.fun/doc/443/

**成功**：zerotier-cli peers 可以看到 planet 角色

**Comment by Jonnyan404** [comment]
感谢提供文档!
已更新到 <https://www.mrdoc.fun/doc/443/> 和 [客户端配置说明](https://github.com/Jonnyan404/zerotier-planet/blob/main/%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.md)
