### ISSUE TITLE
搞了几个小时，装好公网planet，三个地点的openwrt都连接上了，最后路由器NAT功能无法使用。

### ISSUE THREAD

**Issue by LemonRua** [Jonnyan404/zerotier-planet#36]
搞了几个小时，装好公网planet，三个地点的openwrt都连接上了，且每台设备都能看到PLANET。

但是，就是路由器NAT功能无法使用。

设置都和之前用官网的版本一样。各种重启服务和刷新。没响应。

![PixPin_2024-04-05_23-19-11](https://github.com/Jonnyan404/zerotier-planet/assets/111273857/29a07845-3155-45a4-bcad-caf73bc40500)

![PixPin_2024-04-05_23-20-28](https://github.com/Jonnyan404/zerotier-planet/assets/111273857/9b936846-595a-440a-987e-0e75cb205963)

不知道是不是我自己的原因。如果有大佬解决了这个问题可以回复我一下。

还是建议小白用官网的版本＋moon吧。至少这个在我们这边还是畅联的。

**Comment by Gxyloj** [comment]
openwrt防火墙和zt虚拟网卡的接口需要配置
防火墙自定义规则
----------------------
iptables -t nat -A POSTROUTING -j MASQUERADE

**Comment by LemonRua** [comment]
> ## openwrt防火墙和zt虚拟网卡的接口需要配置
> 防火墙自定义规则
> iptables -t nat -A POSTROUTING -j MASQUERADE

**很感谢你的帮助，虽然也没有成功，不知道问题出在了哪里。作为一个小白还是全部用回了官方的加一个自己的Moon算了。**
