### ISSUE TITLE
执行  docker-compose up -d 出错

### ISSUE THREAD

**Issue by hacperme** [Jonnyan404/zerotier-planet#4]
为啥提示版本不支持呢？

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**Comment by Jonnyan404** [comment]
因为你的docker版本有点低，我刚改过了，你重新拉取一遍就好了。

**Comment by hacperme** [comment]
> 因为你的docker版本有点低，我刚改过了，你重新拉取一遍就好了。

好的，可以了，👍

**Comment by Jonnyan404** [comment]
done
