### ISSUE TITLE
执行 docker-compose up -d 显示-bash: docker-compose: command not found

### ISSUE THREAD

**Issue by springletx** [Jonnyan404/zerotier-planet#5]
![image](https://user-images.githubusercontent.com/29573988/144821326-41ba54e1-2b0e-4cd7-96f1-36b429d7b214.png)
新手小白，请指点一下，谢谢

[root@racknerd-edd664 zerotier-planet]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Mon Jun  7 15:36:09 2021
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-208.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Mon Jun  7 15:36:09 2021
 OS/Arch:         linux/amd64
 Experimental:    false
[root@racknerd-edd664 zerotier-planet]# ll
total 44
-rw-r--r-- 1 root root   498 Dec  6 17:13 docker-compose.yml
-rw-r--r-- 1 root root 35149 Dec  6 17:13 LICENSE
-rw-r--r-- 1 root root  1057 Dec  6 17:13 README.md
[root@racknerd-edd664 zerotier-planet]# docker-compose up -d
-bash: docker-compose: command not found

**Comment by Jonnyan404** [comment]
你的docker-compose命令没有安装.安装的话,你可以自行搜索.
或者
直接执行:`docker run --restart=on-failure:3 -d --name ztncui -e HTTP_PORT=4000 -e HTTP_ALL_INTERFACES=yes -e ZTNCUI_PASSWD=mrdoc.fun -p 4000:4000 keynetworks/ztncui`等效于上面的docker-compose.

**Comment by springletx** [comment]
按您的方法解决了，十分感谢！
