### ISSUE TITLE
win7和群晖客户端显示离线

### ISSUE THREAD

**Issue by springletx** [Jonnyan404/zerotier-planet#6]
![Snipaste_2021-12-09_10-45-26](https://user-images.githubusercontent.com/29573988/145326664-5c71a730-733a-4e0f-b5b3-a2558e89b4f1.png)
三台设备都在线且能相互ping通，速度也很不错，但是win7客户端和群晖的客户端（群晖版本号6.1用的是官方对应版本的客户端）在服务器端显示离线，唯一显示在线的那台是win11。
麻烦问一下这是什么问题？
谢谢

**Comment by Jonnyan404** [comment]
可能缓存吧,清理缓存看看~~~
还不行的话,去ztncui项目作者那里找找看.
