### ISSUE TITLE
虚假的planet服务器,真实的网络控制器

### ISSUE THREAD

**Issue by LGinC** [Jonnyan404/zerotier-planet#9]
ztncui是网络控制器,不是行星服务器, ztncui只是提供了网络id注册功能, 真正的planet还是zerotier官方的.
证据就是执行`zertotier-cli listpeers`可以看到planet都是官方的ip,而自己服务器的ip是leaf.
也就是说并没有完全和官方的网络隔离

**Comment by waynevan** [comment]
我在国内服务器上搭建的，ping服务器十几毫秒，ping其他节点500毫秒

**Comment by imwyh** [comment]
理论上如果要完全整一个私有的服务器，至少要在客户端设置plant的ip。如果没有以上步骤，那么肯定会先连接官方plant后连私服。

**Comment by jqtmviyu** [comment]
https://github.com/Jonnyan404/zerotier-planet/issues/11#issuecomment-1059961262

**Comment by Jonnyan404** [comment]
已添加补丁，请查看最新文档。
